package main

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/esrrhs/gohome/network"
)

const (
	defaultGenServerFile = "config_server.json"
	secretBytes          = 16 // 32 hex chars; strong enough and not a known weak default
	defaultClientHost    = "127.0.0.1"
)

// clientModes are the proxy modes generated by -genconfig.
var clientModes = []struct {
	Type string
	File string
	Name string
}{
	{Type: "proxy_client", File: "config_proxy_client.json", Name: "proxy_client"},
	{Type: "reverse_proxy_client", File: "config_reverse_proxy_client.json", Name: "reverse_proxy_client"},
	{Type: "socks5_client", File: "config_socks5_client.json", Name: "socks5_client"},
	{Type: "reverse_socks5_client", File: "config_reverse_socks5_client.json", Name: "reverse_socks5_client"},
	{Type: "http_client", File: "config_http_client.json", Name: "http_client"},
	{Type: "reverse_http_client", File: "config_reverse_http_client.json", Name: "reverse_http_client"},
}

func randomSecret() (string, error) {
	b := make([]byte, secretBytes)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func ptrString(s string) *string { return &s }
func ptrInt(v int) *int       { return &v }

// defaultListenAddr returns a sensible listen address for each underlay proto.
func defaultListenAddr(proto string, index int) string {
	switch strings.ToLower(proto) {
	case "tcp":
		return ":8888"
	case "rudp":
		return ":8889"
	case "ricmp":
		return "0.0.0.0"
	case "kcp":
		return ":8890"
	case "quic":
		return ":8891"
	case "rhttp":
		return ":8892"
	default:
		return fmt.Sprintf(":%d", 8888+index)
	}
}

// defaultServerAddr is what a client dials for a given underlay proto.
func defaultServerAddr(proto, host string, index int) string {
	if host == "" {
		host = defaultClientHost
	}
	switch strings.ToLower(proto) {
	case "ricmp":
		return host
	default:
		listen := defaultListenAddr(proto, index)
		if strings.HasPrefix(listen, ":") {
			return host + listen
		}
		return netJoinHostPort(host, listen)
	}
}

func netJoinHostPort(host, addr string) string {
	// addr may already be host:port; keep simple for our generated listens.
	if strings.Contains(addr, ":") && !strings.HasPrefix(addr, ":") {
		return addr
	}
	return host + addr
}

func allMainProtos() []string {
	return append([]string(nil), network.SupportReliableProtos()...)
}

func allMainListens(protos []string) []string {
	out := make([]string, len(protos))
	for i, p := range protos {
		out[i] = defaultListenAddr(p, i)
	}
	return out
}

func allMainServers(protos []string, host string) []string {
	out := make([]string, len(protos))
	for i, p := range protos {
		out[i] = defaultServerAddr(p, host, i)
	}
	return out
}

func commonDefaults(key, encrypt string) ConfigFile {
	return ConfigFile{
		Key:          key,
		Encrypt:      ptrString(encrypt),
		EncryptType:  ptrString("chacha20"),
		Compress:     ptrInt(128),
		CompressType: ptrString("zstd"),
		LogLevel:     "info",
		NoLog:        ptrInt(0),
		NoPrint:      ptrInt(0),
	}
}

func defaultServerConfig(key, encrypt string) ConfigFile {
	protos := allMainProtos()
	cfg := commonDefaults(key, encrypt)
	cfg.Type = "server"
	cfg.Proto = protos
	cfg.Listen = allMainListens(protos)
	cfg.MaxClient = ptrInt(10000)
	cfg.MaxConn = ptrInt(10240)
	return cfg
}

func defaultClientConfig(clientType, key, encrypt string) (ConfigFile, error) {
	clientType = strings.ToLower(strings.TrimSpace(clientType))
	protos := allMainProtos()
	cfg := commonDefaults(key, encrypt)
	cfg.Type = clientType
	cfg.Proto = protos
	cfg.Servers = allMainServers(protos, defaultClientHost)

	switch clientType {
	case "proxy_client":
		cfg.Name = "proxy_client"
		cfg.ProxyProto = []string{"tcp"}
		cfg.FromAddr = []string{":8080"}
		cfg.ToAddr = []string{":8080"}
	case "reverse_proxy_client":
		cfg.Name = "reverse_proxy_client"
		cfg.ProxyProto = []string{"tcp"}
		cfg.FromAddr = []string{":8080"}
		cfg.ToAddr = []string{":8080"}
	case "socks5_client":
		cfg.Name = "socks5_client"
		cfg.ProxyProto = []string{"tcp"}
		cfg.FromAddr = []string{":1080"}
	case "reverse_socks5_client":
		cfg.Name = "reverse_socks5_client"
		cfg.ProxyProto = []string{"tcp"}
		cfg.FromAddr = []string{":1080"}
	case "http_client":
		cfg.Name = "http_client"
		cfg.ProxyProto = []string{"tcp"}
		cfg.FromAddr = []string{":8081"}
	case "reverse_http_client":
		cfg.Name = "reverse_http_client"
		cfg.ProxyProto = []string{"tcp"}
		cfg.FromAddr = []string{":8081"}
	default:
		return ConfigFile{}, fmt.Errorf("unsupported client type: %s", clientType)
	}
	return cfg, nil
}

func writeJSONConfig(path string, cfg ConfigFile, force bool) error {
	if !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s already exists (use -force to overwrite)", path)
		} else if !os.IsNotExist(err) {
			return err
		}
	}
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	dir := filepath.Dir(path)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	return os.WriteFile(path, data, 0o600)
}

// generateConfigs writes one multi-path server config and one client config per proxy mode.
func generateConfigs(outdir string, force bool) error {
	if outdir == "" {
		outdir = "."
	}
	key, err := randomSecret()
	if err != nil {
		return err
	}
	encrypt, err := randomSecret()
	if err != nil {
		return err
	}

	serverCfg := defaultServerConfig(key, encrypt)
	serverPath := filepath.Join(outdir, defaultGenServerFile)
	if err := writeJSONConfig(serverPath, serverCfg, force); err != nil {
		return err
	}

	fmt.Printf("generated %s\n", serverPath)
	paths := []string{serverPath}
	for _, mode := range clientModes {
		cfg, err := defaultClientConfig(mode.Type, key, encrypt)
		if err != nil {
			return err
		}
		path := filepath.Join(outdir, mode.File)
		if err := writeJSONConfig(path, cfg, force); err != nil {
			return err
		}
		fmt.Printf("generated %s\n", path)
		paths = append(paths, path)
	}

	fmt.Println()
	fmt.Println("shared auth/encrypt keys filled with random secrets")
	fmt.Printf("server listens all main channels: %v\n", serverCfg.Proto)
	fmt.Printf("clients dial all main channels:   %v\n", serverCfg.Proto)
	fmt.Println()
	fmt.Printf("start server:              ./spp -config %s\n", serverPath)
	fmt.Printf("start forward proxy:       ./spp -config %s\n", filepath.Join(outdir, "config_proxy_client.json"))
	fmt.Printf("start reverse proxy:       ./spp -config %s\n", filepath.Join(outdir, "config_reverse_proxy_client.json"))
	fmt.Printf("start socks5 proxy:        ./spp -config %s\n", filepath.Join(outdir, "config_socks5_client.json"))
	fmt.Printf("start reverse socks5:      ./spp -config %s\n", filepath.Join(outdir, "config_reverse_socks5_client.json"))
	fmt.Printf("start http proxy:          ./spp -config %s\n", filepath.Join(outdir, "config_http_client.json"))
	fmt.Printf("start reverse http proxy:  ./spp -config %s\n", filepath.Join(outdir, "config_reverse_http_client.json"))
	_ = paths
	return nil
}
