// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frp.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SrpFrame_TYPE int32

const (
	SrpFrame_LOGIN    SrpFrame_TYPE = 0
	SrpFrame_LOGINRSP SrpFrame_TYPE = 1
	SrpFrame_DATA     SrpFrame_TYPE = 2
	SrpFrame_HB       SrpFrame_TYPE = 3
	SrpFrame_OPEN     SrpFrame_TYPE = 4
	SrpFrame_CLOSE    SrpFrame_TYPE = 5
)

var SrpFrame_TYPE_name = map[int32]string{
	0: "LOGIN",
	1: "LOGINRSP",
	2: "DATA",
	3: "HB",
	4: "OPEN",
	5: "CLOSE",
}

var SrpFrame_TYPE_value = map[string]int32{
	"LOGIN":    0,
	"LOGINRSP": 1,
	"DATA":     2,
	"HB":       3,
	"OPEN":     4,
	"CLOSE":    5,
}

func (x SrpFrame_TYPE) String() string {
	return proto.EnumName(SrpFrame_TYPE_name, int32(x))
}

func (SrpFrame_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d316925312aba732, []int{6, 0}
}

type SrpLoginFrame struct {
	Remote               string   `protobuf:"bytes,1,opt,name=remote,proto3" json:"remote,omitempty"`
	Compress             int32    `protobuf:"varint,2,opt,name=compress,proto3" json:"compress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrpLoginFrame) Reset()         { *m = SrpLoginFrame{} }
func (m *SrpLoginFrame) String() string { return proto.CompactTextString(m) }
func (*SrpLoginFrame) ProtoMessage()    {}
func (*SrpLoginFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_d316925312aba732, []int{0}
}

func (m *SrpLoginFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrpLoginFrame.Unmarshal(m, b)
}
func (m *SrpLoginFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrpLoginFrame.Marshal(b, m, deterministic)
}
func (m *SrpLoginFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrpLoginFrame.Merge(m, src)
}
func (m *SrpLoginFrame) XXX_Size() int {
	return xxx_messageInfo_SrpLoginFrame.Size(m)
}
func (m *SrpLoginFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_SrpLoginFrame.DiscardUnknown(m)
}

var xxx_messageInfo_SrpLoginFrame proto.InternalMessageInfo

func (m *SrpLoginFrame) GetRemote() string {
	if m != nil {
		return m.Remote
	}
	return ""
}

func (m *SrpLoginFrame) GetCompress() int32 {
	if m != nil {
		return m.Compress
	}
	return 0
}

type SrpLoginRspFrame struct {
	Ret                  bool     `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrpLoginRspFrame) Reset()         { *m = SrpLoginRspFrame{} }
func (m *SrpLoginRspFrame) String() string { return proto.CompactTextString(m) }
func (*SrpLoginRspFrame) ProtoMessage()    {}
func (*SrpLoginRspFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_d316925312aba732, []int{1}
}

func (m *SrpLoginRspFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrpLoginRspFrame.Unmarshal(m, b)
}
func (m *SrpLoginRspFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrpLoginRspFrame.Marshal(b, m, deterministic)
}
func (m *SrpLoginRspFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrpLoginRspFrame.Merge(m, src)
}
func (m *SrpLoginRspFrame) XXX_Size() int {
	return xxx_messageInfo_SrpLoginRspFrame.Size(m)
}
func (m *SrpLoginRspFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_SrpLoginRspFrame.DiscardUnknown(m)
}

var xxx_messageInfo_SrpLoginRspFrame proto.InternalMessageInfo

func (m *SrpLoginRspFrame) GetRet() bool {
	if m != nil {
		return m.Ret
	}
	return false
}

func (m *SrpLoginRspFrame) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SrpHBFrame struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrpHBFrame) Reset()         { *m = SrpHBFrame{} }
func (m *SrpHBFrame) String() string { return proto.CompactTextString(m) }
func (*SrpHBFrame) ProtoMessage()    {}
func (*SrpHBFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_d316925312aba732, []int{2}
}

func (m *SrpHBFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrpHBFrame.Unmarshal(m, b)
}
func (m *SrpHBFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrpHBFrame.Marshal(b, m, deterministic)
}
func (m *SrpHBFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrpHBFrame.Merge(m, src)
}
func (m *SrpHBFrame) XXX_Size() int {
	return xxx_messageInfo_SrpHBFrame.Size(m)
}
func (m *SrpHBFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_SrpHBFrame.DiscardUnknown(m)
}

var xxx_messageInfo_SrpHBFrame proto.InternalMessageInfo

func (m *SrpHBFrame) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type SrpOpenFrame struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrpOpenFrame) Reset()         { *m = SrpOpenFrame{} }
func (m *SrpOpenFrame) String() string { return proto.CompactTextString(m) }
func (*SrpOpenFrame) ProtoMessage()    {}
func (*SrpOpenFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_d316925312aba732, []int{3}
}

func (m *SrpOpenFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrpOpenFrame.Unmarshal(m, b)
}
func (m *SrpOpenFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrpOpenFrame.Marshal(b, m, deterministic)
}
func (m *SrpOpenFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrpOpenFrame.Merge(m, src)
}
func (m *SrpOpenFrame) XXX_Size() int {
	return xxx_messageInfo_SrpOpenFrame.Size(m)
}
func (m *SrpOpenFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_SrpOpenFrame.DiscardUnknown(m)
}

var xxx_messageInfo_SrpOpenFrame proto.InternalMessageInfo

func (m *SrpOpenFrame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SrpCloseFrame struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrpCloseFrame) Reset()         { *m = SrpCloseFrame{} }
func (m *SrpCloseFrame) String() string { return proto.CompactTextString(m) }
func (*SrpCloseFrame) ProtoMessage()    {}
func (*SrpCloseFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_d316925312aba732, []int{4}
}

func (m *SrpCloseFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrpCloseFrame.Unmarshal(m, b)
}
func (m *SrpCloseFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrpCloseFrame.Marshal(b, m, deterministic)
}
func (m *SrpCloseFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrpCloseFrame.Merge(m, src)
}
func (m *SrpCloseFrame) XXX_Size() int {
	return xxx_messageInfo_SrpCloseFrame.Size(m)
}
func (m *SrpCloseFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_SrpCloseFrame.DiscardUnknown(m)
}

var xxx_messageInfo_SrpCloseFrame proto.InternalMessageInfo

func (m *SrpCloseFrame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SrpDataFrame struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Compress             bool     `protobuf:"varint,2,opt,name=compress,proto3" json:"compress,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrpDataFrame) Reset()         { *m = SrpDataFrame{} }
func (m *SrpDataFrame) String() string { return proto.CompactTextString(m) }
func (*SrpDataFrame) ProtoMessage()    {}
func (*SrpDataFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_d316925312aba732, []int{5}
}

func (m *SrpDataFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrpDataFrame.Unmarshal(m, b)
}
func (m *SrpDataFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrpDataFrame.Marshal(b, m, deterministic)
}
func (m *SrpDataFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrpDataFrame.Merge(m, src)
}
func (m *SrpDataFrame) XXX_Size() int {
	return xxx_messageInfo_SrpDataFrame.Size(m)
}
func (m *SrpDataFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_SrpDataFrame.DiscardUnknown(m)
}

var xxx_messageInfo_SrpDataFrame proto.InternalMessageInfo

func (m *SrpDataFrame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SrpDataFrame) GetCompress() bool {
	if m != nil {
		return m.Compress
	}
	return false
}

func (m *SrpDataFrame) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SrpFrame struct {
	Type                 SrpFrame_TYPE     `protobuf:"varint,1,opt,name=type,proto3,enum=SrpFrame_TYPE" json:"type,omitempty"`
	LoginFrame           *SrpLoginFrame    `protobuf:"bytes,2,opt,name=loginFrame,proto3" json:"loginFrame,omitempty"`
	LoginRspFrame        *SrpLoginRspFrame `protobuf:"bytes,3,opt,name=loginRspFrame,proto3" json:"loginRspFrame,omitempty"`
	DataFrame            *SrpDataFrame     `protobuf:"bytes,4,opt,name=dataFrame,proto3" json:"dataFrame,omitempty"`
	HbFrame              *SrpHBFrame       `protobuf:"bytes,5,opt,name=hbFrame,proto3" json:"hbFrame,omitempty"`
	OpenFrame            *SrpOpenFrame     `protobuf:"bytes,6,opt,name=openFrame,proto3" json:"openFrame,omitempty"`
	CloseFrame           *SrpCloseFrame    `protobuf:"bytes,7,opt,name=closeFrame,proto3" json:"closeFrame,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SrpFrame) Reset()         { *m = SrpFrame{} }
func (m *SrpFrame) String() string { return proto.CompactTextString(m) }
func (*SrpFrame) ProtoMessage()    {}
func (*SrpFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_d316925312aba732, []int{6}
}

func (m *SrpFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrpFrame.Unmarshal(m, b)
}
func (m *SrpFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrpFrame.Marshal(b, m, deterministic)
}
func (m *SrpFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrpFrame.Merge(m, src)
}
func (m *SrpFrame) XXX_Size() int {
	return xxx_messageInfo_SrpFrame.Size(m)
}
func (m *SrpFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_SrpFrame.DiscardUnknown(m)
}

var xxx_messageInfo_SrpFrame proto.InternalMessageInfo

func (m *SrpFrame) GetType() SrpFrame_TYPE {
	if m != nil {
		return m.Type
	}
	return SrpFrame_LOGIN
}

func (m *SrpFrame) GetLoginFrame() *SrpLoginFrame {
	if m != nil {
		return m.LoginFrame
	}
	return nil
}

func (m *SrpFrame) GetLoginRspFrame() *SrpLoginRspFrame {
	if m != nil {
		return m.LoginRspFrame
	}
	return nil
}

func (m *SrpFrame) GetDataFrame() *SrpDataFrame {
	if m != nil {
		return m.DataFrame
	}
	return nil
}

func (m *SrpFrame) GetHbFrame() *SrpHBFrame {
	if m != nil {
		return m.HbFrame
	}
	return nil
}

func (m *SrpFrame) GetOpenFrame() *SrpOpenFrame {
	if m != nil {
		return m.OpenFrame
	}
	return nil
}

func (m *SrpFrame) GetCloseFrame() *SrpCloseFrame {
	if m != nil {
		return m.CloseFrame
	}
	return nil
}

func init() {
	proto.RegisterEnum("SrpFrame_TYPE", SrpFrame_TYPE_name, SrpFrame_TYPE_value)
	proto.RegisterType((*SrpLoginFrame)(nil), "SrpLoginFrame")
	proto.RegisterType((*SrpLoginRspFrame)(nil), "SrpLoginRspFrame")
	proto.RegisterType((*SrpHBFrame)(nil), "SrpHBFrame")
	proto.RegisterType((*SrpOpenFrame)(nil), "SrpOpenFrame")
	proto.RegisterType((*SrpCloseFrame)(nil), "SrpCloseFrame")
	proto.RegisterType((*SrpDataFrame)(nil), "SrpDataFrame")
	proto.RegisterType((*SrpFrame)(nil), "SrpFrame")
}

func init() { proto.RegisterFile("frp.proto", fileDescriptor_d316925312aba732) }

var fileDescriptor_d316925312aba732 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcb, 0x8a, 0xdb, 0x40,
	0x10, 0x8c, 0x9e, 0x96, 0xda, 0x0f, 0x26, 0x73, 0x08, 0x22, 0x87, 0x44, 0x0c, 0x04, 0x0c, 0x01,
	0x1d, 0x1c, 0x48, 0xce, 0x7e, 0xc6, 0x01, 0x63, 0x99, 0x91, 0x2f, 0xd9, 0x9b, 0x6c, 0x69, 0xbd,
	0x02, 0xcb, 0x1a, 0x46, 0xba, 0xec, 0x5f, 0xec, 0x27, 0x2f, 0x33, 0x7a, 0x8c, 0x76, 0xd7, 0xb7,
	0xd6, 0x54, 0x75, 0x75, 0x57, 0xb5, 0xc0, 0x7d, 0xe4, 0x2c, 0x60, 0xbc, 0xa8, 0x0a, 0xb2, 0x84,
	0x71, 0xc4, 0xd9, 0xae, 0xb8, 0x64, 0xb7, 0x0d, 0x8f, 0xf3, 0x14, 0x7f, 0x01, 0x9b, 0xa7, 0x79,
	0x51, 0xa5, 0x9e, 0xe6, 0x6b, 0x53, 0x97, 0x36, 0x5f, 0xf8, 0x2b, 0x38, 0xe7, 0x22, 0x67, 0x3c,
	0x2d, 0x4b, 0x4f, 0xf7, 0xb5, 0xa9, 0x45, 0xbb, 0x6f, 0xf2, 0x1b, 0x50, 0x2b, 0x42, 0x4b, 0x56,
	0xeb, 0x20, 0x30, 0x78, 0x5a, 0x49, 0x11, 0x87, 0x8a, 0x52, 0xbc, 0xe4, 0xe5, 0x45, 0x36, 0xbb,
	0x54, 0x94, 0xc4, 0x07, 0x88, 0x38, 0xdb, 0x2e, 0xea, 0x0e, 0x0c, 0x66, 0x95, 0xe5, 0xf5, 0x5c,
	0x83, 0xca, 0x9a, 0x7c, 0x83, 0x51, 0xc4, 0x59, 0xc8, 0xd2, 0x66, 0xbb, 0x09, 0xe8, 0x59, 0xd2,
	0x6c, 0xa6, 0x67, 0x09, 0xf9, 0x2e, 0xd7, 0x5f, 0x5e, 0x8b, 0x32, 0xbd, 0x4f, 0xd8, 0x4b, 0x81,
	0x55, 0x5c, 0xc5, 0x77, 0xf1, 0x0f, 0xb6, 0x1c, 0x65, 0x4b, 0x2c, 0x94, 0xc4, 0x55, 0xec, 0x19,
	0xbe, 0x36, 0x1d, 0x51, 0x59, 0x93, 0x17, 0x03, 0x9c, 0x88, 0x37, 0x1e, 0x09, 0x98, 0xd5, 0x33,
	0xab, 0x37, 0x9e, 0xcc, 0x26, 0x41, 0x0b, 0x04, 0xc7, 0xff, 0x87, 0x35, 0x95, 0x18, 0x0e, 0x00,
	0xae, 0x5d, 0xba, 0x72, 0xc4, 0xb0, 0x66, 0xaa, 0xcc, 0x69, 0x8f, 0x81, 0xff, 0xc0, 0xf8, 0xda,
	0x0f, 0x52, 0x4e, 0x1f, 0xce, 0x3e, 0x07, 0xef, 0x13, 0xa6, 0x6f, 0x79, 0xf8, 0x27, 0xb8, 0x49,
	0x6b, 0xd3, 0x33, 0x65, 0xd3, 0x38, 0xe8, 0x7b, 0xa7, 0x0a, 0xc7, 0x3f, 0x60, 0xf0, 0x74, 0xaa,
	0xa9, 0x96, 0xa4, 0x0e, 0x03, 0x75, 0x09, 0xda, 0x62, 0x42, 0xb3, 0x68, 0xb3, 0xf7, 0x6c, 0xa5,
	0xd9, 0x1d, 0x84, 0x2a, 0x5c, 0x38, 0x3d, 0x77, 0x87, 0xf0, 0x06, 0xca, 0xa9, 0x3a, 0x0f, 0xed,
	0x31, 0xc8, 0x06, 0x4c, 0x91, 0x13, 0x76, 0xc1, 0xda, 0x85, 0x7f, 0xff, 0xed, 0xd1, 0x27, 0x3c,
	0x02, 0x47, 0x96, 0x34, 0x3a, 0x20, 0x0d, 0x3b, 0x60, 0xae, 0xe6, 0xc7, 0x39, 0xd2, 0xb1, 0x0d,
	0xfa, 0x76, 0x81, 0x0c, 0xf1, 0x12, 0x1e, 0xd6, 0x7b, 0x64, 0x8a, 0xa6, 0xe5, 0x2e, 0x8c, 0xd6,
	0xc8, 0x5a, 0xd8, 0x0f, 0x66, 0x1e, 0x67, 0xb7, 0x93, 0x2d, 0xff, 0xe8, 0x5f, 0xaf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x19, 0x52, 0x5e, 0xfc, 0xde, 0x02, 0x00, 0x00,
}
