// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.5.0
// source: proxy.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PROXY_PROTO int32

const (
	PROXY_PROTO_TCP   PROXY_PROTO = 0
	PROXY_PROTO_UDP   PROXY_PROTO = 1
	PROXY_PROTO_RUDP  PROXY_PROTO = 2
	PROXY_PROTO_RICMP PROXY_PROTO = 3
	PROXY_PROTO_KCP   PROXY_PROTO = 4
)

// Enum value maps for PROXY_PROTO.
var (
	PROXY_PROTO_name = map[int32]string{
		0: "TCP",
		1: "UDP",
		2: "RUDP",
		3: "RICMP",
		4: "KCP",
	}
	PROXY_PROTO_value = map[string]int32{
		"TCP":   0,
		"UDP":   1,
		"RUDP":  2,
		"RICMP": 3,
		"KCP":   4,
	}
)

func (x PROXY_PROTO) Enum() *PROXY_PROTO {
	p := new(PROXY_PROTO)
	*p = x
	return p
}

func (x PROXY_PROTO) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PROXY_PROTO) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proto_enumTypes[0].Descriptor()
}

func (PROXY_PROTO) Type() protoreflect.EnumType {
	return &file_proxy_proto_enumTypes[0]
}

func (x PROXY_PROTO) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PROXY_PROTO.Descriptor instead.
func (PROXY_PROTO) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

type CLIENT_TYPE int32

const (
	// client fromaddr -> server toaddr
	CLIENT_TYPE_PROXY CLIENT_TYPE = 0
	// server fromaddr -> client toaddr
	CLIENT_TYPE_REVERSE_PROXY CLIENT_TYPE = 1
	// client fromaddr -> server
	CLIENT_TYPE_SOCKS5 CLIENT_TYPE = 2
	// server fromaddr -> client
	CLIENT_TYPE_REVERSE_SOCKS5 CLIENT_TYPE = 3
	// client fromaddr -> server shadowsocks address [SS_LOCAL_HOST:SS_LOCAL_PORT]
	CLIENT_TYPE_SS_PROXY CLIENT_TYPE = 4
)

// Enum value maps for CLIENT_TYPE.
var (
	CLIENT_TYPE_name = map[int32]string{
		0: "PROXY",
		1: "REVERSE_PROXY",
		2: "SOCKS5",
		3: "REVERSE_SOCKS5",
		4: "SS_PROXY",
	}
	CLIENT_TYPE_value = map[string]int32{
		"PROXY":          0,
		"REVERSE_PROXY":  1,
		"SOCKS5":         2,
		"REVERSE_SOCKS5": 3,
		"SS_PROXY":       4,
	}
)

func (x CLIENT_TYPE) Enum() *CLIENT_TYPE {
	p := new(CLIENT_TYPE)
	*p = x
	return p
}

func (x CLIENT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CLIENT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proto_enumTypes[1].Descriptor()
}

func (CLIENT_TYPE) Type() protoreflect.EnumType {
	return &file_proxy_proto_enumTypes[1]
}

func (x CLIENT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CLIENT_TYPE.Descriptor instead.
func (CLIENT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{1}
}

// COMPRESS_TYPE selects payload compression. UNSPECIFIED means "use peer default".
type COMPRESS_TYPE int32

const (
	COMPRESS_TYPE_COMPRESS_UNSPECIFIED COMPRESS_TYPE = 0
	COMPRESS_TYPE_COMPRESS_NONE        COMPRESS_TYPE = 1
	COMPRESS_TYPE_COMPRESS_ZLIB        COMPRESS_TYPE = 2
	COMPRESS_TYPE_COMPRESS_ZSTD        COMPRESS_TYPE = 3
)

// Enum value maps for COMPRESS_TYPE.
var (
	COMPRESS_TYPE_name = map[int32]string{
		0: "COMPRESS_UNSPECIFIED",
		1: "COMPRESS_NONE",
		2: "COMPRESS_ZLIB",
		3: "COMPRESS_ZSTD",
	}
	COMPRESS_TYPE_value = map[string]int32{
		"COMPRESS_UNSPECIFIED": 0,
		"COMPRESS_NONE":        1,
		"COMPRESS_ZLIB":        2,
		"COMPRESS_ZSTD":        3,
	}
)

func (x COMPRESS_TYPE) Enum() *COMPRESS_TYPE {
	p := new(COMPRESS_TYPE)
	*p = x
	return p
}

func (x COMPRESS_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (COMPRESS_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proto_enumTypes[2].Descriptor()
}

func (COMPRESS_TYPE) Type() protoreflect.EnumType {
	return &file_proxy_proto_enumTypes[2]
}

func (x COMPRESS_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use COMPRESS_TYPE.Descriptor instead.
func (COMPRESS_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{2}
}

// ENCRYPT_TYPE selects payload encryption. UNSPECIFIED means "use peer default".
type ENCRYPT_TYPE int32

const (
	ENCRYPT_TYPE_ENCRYPT_UNSPECIFIED ENCRYPT_TYPE = 0
	ENCRYPT_TYPE_ENCRYPT_NONE        ENCRYPT_TYPE = 1
	ENCRYPT_TYPE_ENCRYPT_RC4         ENCRYPT_TYPE = 2
)

// Enum value maps for ENCRYPT_TYPE.
var (
	ENCRYPT_TYPE_name = map[int32]string{
		0: "ENCRYPT_UNSPECIFIED",
		1: "ENCRYPT_NONE",
		2: "ENCRYPT_RC4",
	}
	ENCRYPT_TYPE_value = map[string]int32{
		"ENCRYPT_UNSPECIFIED": 0,
		"ENCRYPT_NONE":        1,
		"ENCRYPT_RC4":         2,
	}
)

func (x ENCRYPT_TYPE) Enum() *ENCRYPT_TYPE {
	p := new(ENCRYPT_TYPE)
	*p = x
	return p
}

func (x ENCRYPT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ENCRYPT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proto_enumTypes[3].Descriptor()
}

func (ENCRYPT_TYPE) Type() protoreflect.EnumType {
	return &file_proxy_proto_enumTypes[3]
}

func (x ENCRYPT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ENCRYPT_TYPE.Descriptor instead.
func (ENCRYPT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{3}
}

type FRAME_TYPE int32

const (
	FRAME_TYPE_LOGIN    FRAME_TYPE = 0
	FRAME_TYPE_LOGINRSP FRAME_TYPE = 1
	FRAME_TYPE_DATA     FRAME_TYPE = 2
	FRAME_TYPE_PING     FRAME_TYPE = 3
	FRAME_TYPE_PONG     FRAME_TYPE = 4
	FRAME_TYPE_OPEN     FRAME_TYPE = 5
	FRAME_TYPE_OPENRSP  FRAME_TYPE = 6
	FRAME_TYPE_CLOSE    FRAME_TYPE = 7
)

// Enum value maps for FRAME_TYPE.
var (
	FRAME_TYPE_name = map[int32]string{
		0: "LOGIN",
		1: "LOGINRSP",
		2: "DATA",
		3: "PING",
		4: "PONG",
		5: "OPEN",
		6: "OPENRSP",
		7: "CLOSE",
	}
	FRAME_TYPE_value = map[string]int32{
		"LOGIN":    0,
		"LOGINRSP": 1,
		"DATA":     2,
		"PING":     3,
		"PONG":     4,
		"OPEN":     5,
		"OPENRSP":  6,
		"CLOSE":    7,
	}
)

func (x FRAME_TYPE) Enum() *FRAME_TYPE {
	p := new(FRAME_TYPE)
	*p = x
	return p
}

func (x FRAME_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FRAME_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proto_enumTypes[4].Descriptor()
}

func (FRAME_TYPE) Type() protoreflect.EnumType {
	return &file_proxy_proto_enumTypes[4]
}

func (x FRAME_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FRAME_TYPE.Descriptor instead.
func (FRAME_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{4}
}

type LoginFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proxyproto    PROXY_PROTO            `protobuf:"varint,1,opt,name=proxyproto,proto3,enum=PROXY_PROTO" json:"proxyproto,omitempty"`
	Clienttype    CLIENT_TYPE            `protobuf:"varint,2,opt,name=clienttype,proto3,enum=CLIENT_TYPE" json:"clienttype,omitempty"`
	Fromaddr      string                 `protobuf:"bytes,3,opt,name=fromaddr,proto3" json:"fromaddr,omitempty"`
	Toaddr        string                 `protobuf:"bytes,4,opt,name=toaddr,proto3" json:"toaddr,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Key           string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	CompressType  COMPRESS_TYPE          `protobuf:"varint,7,opt,name=compress_type,json=compressType,proto3,enum=COMPRESS_TYPE" json:"compress_type,omitempty"`
	EncryptType   ENCRYPT_TYPE           `protobuf:"varint,8,opt,name=encrypt_type,json=encryptType,proto3,enum=ENCRYPT_TYPE" json:"encrypt_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginFrame) Reset() {
	*x = LoginFrame{}
	mi := &file_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginFrame) ProtoMessage() {}

func (x *LoginFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginFrame.ProtoReflect.Descriptor instead.
func (*LoginFrame) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *LoginFrame) GetProxyproto() PROXY_PROTO {
	if x != nil {
		return x.Proxyproto
	}
	return PROXY_PROTO_TCP
}

func (x *LoginFrame) GetClienttype() CLIENT_TYPE {
	if x != nil {
		return x.Clienttype
	}
	return CLIENT_TYPE_PROXY
}

func (x *LoginFrame) GetFromaddr() string {
	if x != nil {
		return x.Fromaddr
	}
	return ""
}

func (x *LoginFrame) GetToaddr() string {
	if x != nil {
		return x.Toaddr
	}
	return ""
}

func (x *LoginFrame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginFrame) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LoginFrame) GetCompressType() COMPRESS_TYPE {
	if x != nil {
		return x.CompressType
	}
	return COMPRESS_TYPE_COMPRESS_UNSPECIFIED
}

func (x *LoginFrame) GetEncryptType() ENCRYPT_TYPE {
	if x != nil {
		return x.EncryptType
	}
	return ENCRYPT_TYPE_ENCRYPT_UNSPECIFIED
}

type LoginRspFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ret   bool                   `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg   string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// Agreed session codecs (echoed by server on success).
	CompressType  COMPRESS_TYPE `protobuf:"varint,3,opt,name=compress_type,json=compressType,proto3,enum=COMPRESS_TYPE" json:"compress_type,omitempty"`
	EncryptType   ENCRYPT_TYPE  `protobuf:"varint,4,opt,name=encrypt_type,json=encryptType,proto3,enum=ENCRYPT_TYPE" json:"encrypt_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRspFrame) Reset() {
	*x = LoginRspFrame{}
	mi := &file_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRspFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRspFrame) ProtoMessage() {}

func (x *LoginRspFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRspFrame.ProtoReflect.Descriptor instead.
func (*LoginRspFrame) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRspFrame) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *LoginRspFrame) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginRspFrame) GetCompressType() COMPRESS_TYPE {
	if x != nil {
		return x.CompressType
	}
	return COMPRESS_TYPE_COMPRESS_UNSPECIFIED
}

func (x *LoginRspFrame) GetEncryptType() ENCRYPT_TYPE {
	if x != nil {
		return x.EncryptType
	}
	return ENCRYPT_TYPE_ENCRYPT_UNSPECIFIED
}

type PingFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingFrame) Reset() {
	*x = PingFrame{}
	mi := &file_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingFrame) ProtoMessage() {}

func (x *PingFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingFrame.ProtoReflect.Descriptor instead.
func (*PingFrame) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *PingFrame) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type PongFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongFrame) Reset() {
	*x = PongFrame{}
	mi := &file_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongFrame) ProtoMessage() {}

func (x *PongFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongFrame.ProtoReflect.Descriptor instead.
func (*PongFrame) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *PongFrame) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type OpenConnFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Toaddr        string                 `protobuf:"bytes,2,opt,name=toaddr,proto3" json:"toaddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenConnFrame) Reset() {
	*x = OpenConnFrame{}
	mi := &file_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenConnFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenConnFrame) ProtoMessage() {}

func (x *OpenConnFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenConnFrame.ProtoReflect.Descriptor instead.
func (*OpenConnFrame) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *OpenConnFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OpenConnFrame) GetToaddr() string {
	if x != nil {
		return x.Toaddr
	}
	return ""
}

type OpenConnRspFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ret           bool                   `protobuf:"varint,2,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenConnRspFrame) Reset() {
	*x = OpenConnRspFrame{}
	mi := &file_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenConnRspFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenConnRspFrame) ProtoMessage() {}

func (x *OpenConnRspFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenConnRspFrame.ProtoReflect.Descriptor instead.
func (*OpenConnRspFrame) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *OpenConnRspFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OpenConnRspFrame) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *OpenConnRspFrame) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CloseFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseFrame) Reset() {
	*x = CloseFrame{}
	mi := &file_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseFrame) ProtoMessage() {}

func (x *CloseFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseFrame.ProtoReflect.Descriptor instead.
func (*CloseFrame) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *CloseFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DataFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Compress bool                   `protobuf:"varint,2,opt,name=compress,proto3" json:"compress,omitempty"`
	Crc      string                 `protobuf:"bytes,3,opt,name=crc,proto3" json:"crc,omitempty"`
	Data     []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Index    int32                  `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	// Set when compress=true so the peer knows which decoder to use.
	CompressType  COMPRESS_TYPE `protobuf:"varint,6,opt,name=compress_type,json=compressType,proto3,enum=COMPRESS_TYPE" json:"compress_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataFrame) Reset() {
	*x = DataFrame{}
	mi := &file_proxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFrame) ProtoMessage() {}

func (x *DataFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFrame.ProtoReflect.Descriptor instead.
func (*DataFrame) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *DataFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataFrame) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

func (x *DataFrame) GetCrc() string {
	if x != nil {
		return x.Crc
	}
	return ""
}

func (x *DataFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataFrame) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DataFrame) GetCompressType() COMPRESS_TYPE {
	if x != nil {
		return x.CompressType
	}
	return COMPRESS_TYPE_COMPRESS_UNSPECIFIED
}

type ProxyFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FRAME_TYPE             `protobuf:"varint,1,opt,name=type,proto3,enum=FRAME_TYPE" json:"type,omitempty"`
	LoginFrame    *LoginFrame            `protobuf:"bytes,2,opt,name=loginFrame,proto3" json:"loginFrame,omitempty"`
	LoginRspFrame *LoginRspFrame         `protobuf:"bytes,3,opt,name=loginRspFrame,proto3" json:"loginRspFrame,omitempty"`
	DataFrame     *DataFrame             `protobuf:"bytes,4,opt,name=dataFrame,proto3" json:"dataFrame,omitempty"`
	PingFrame     *PingFrame             `protobuf:"bytes,5,opt,name=pingFrame,proto3" json:"pingFrame,omitempty"`
	PongFrame     *PongFrame             `protobuf:"bytes,6,opt,name=pongFrame,proto3" json:"pongFrame,omitempty"`
	OpenFrame     *OpenConnFrame         `protobuf:"bytes,7,opt,name=openFrame,proto3" json:"openFrame,omitempty"`
	OpenRspFrame  *OpenConnRspFrame      `protobuf:"bytes,8,opt,name=openRspFrame,proto3" json:"openRspFrame,omitempty"`
	CloseFrame    *CloseFrame            `protobuf:"bytes,9,opt,name=closeFrame,proto3" json:"closeFrame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyFrame) Reset() {
	*x = ProxyFrame{}
	mi := &file_proxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyFrame) ProtoMessage() {}

func (x *ProxyFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyFrame.ProtoReflect.Descriptor instead.
func (*ProxyFrame) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *ProxyFrame) GetType() FRAME_TYPE {
	if x != nil {
		return x.Type
	}
	return FRAME_TYPE_LOGIN
}

func (x *ProxyFrame) GetLoginFrame() *LoginFrame {
	if x != nil {
		return x.LoginFrame
	}
	return nil
}

func (x *ProxyFrame) GetLoginRspFrame() *LoginRspFrame {
	if x != nil {
		return x.LoginRspFrame
	}
	return nil
}

func (x *ProxyFrame) GetDataFrame() *DataFrame {
	if x != nil {
		return x.DataFrame
	}
	return nil
}

func (x *ProxyFrame) GetPingFrame() *PingFrame {
	if x != nil {
		return x.PingFrame
	}
	return nil
}

func (x *ProxyFrame) GetPongFrame() *PongFrame {
	if x != nil {
		return x.PongFrame
	}
	return nil
}

func (x *ProxyFrame) GetOpenFrame() *OpenConnFrame {
	if x != nil {
		return x.OpenFrame
	}
	return nil
}

func (x *ProxyFrame) GetOpenRspFrame() *OpenConnRspFrame {
	if x != nil {
		return x.OpenRspFrame
	}
	return nil
}

func (x *ProxyFrame) GetCloseFrame() *CloseFrame {
	if x != nil {
		return x.CloseFrame
	}
	return nil
}

var File_proxy_proto protoreflect.FileDescriptor

var file_proxy_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x02,
	0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0c, 0x2e, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2c, 0x0a, 0x0a, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c,
	0x2e, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0a, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d,
	0x61, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x33, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x43, 0x4f, 0x4d, 0x50,
	0x52, 0x45, 0x53, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x0c, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e,
	0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0b, 0x65, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x9a, 0x01, 0x0a, 0x0d, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x33, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53,
	0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x0c, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x45, 0x4e, 0x43,
	0x52, 0x59, 0x50, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0b, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x1f, 0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x09, 0x50, 0x6f, 0x6e, 0x67, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x6e,
	0x43, 0x6f, 0x6e, 0x6e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x61, 0x64, 0x64,
	0x72, 0x22, 0x46, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x73, 0x70,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1c, 0x0a, 0x0a, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa8, 0x01, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x72, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x63, 0x72, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x33, 0x0a,
	0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x22, 0xa0, 0x03, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0b, 0x2e, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12,
	0x34, 0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73,
	0x70, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12,
	0x28, 0x0a, 0x09, 0x70, 0x69, 0x6e, 0x67, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x09,
	0x70, 0x69, 0x6e, 0x67, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x70, 0x6f, 0x6e,
	0x67, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50,
	0x6f, 0x6e, 0x67, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x09, 0x70, 0x6f, 0x6e, 0x67, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x6f, 0x6e,
	0x6e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x12, 0x35, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x6e, 0x52, 0x73, 0x70, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x6f,
	0x6e, 0x6e, 0x52, 0x73, 0x70, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x6e,
	0x52, 0x73, 0x70, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x73,
	0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x2a, 0x3d, 0x0a, 0x0b, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f, 0x50,
	0x52, 0x4f, 0x54, 0x4f, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x55, 0x44, 0x50, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x55, 0x44, 0x50, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x52, 0x49, 0x43, 0x4d, 0x50, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x4b,
	0x43, 0x50, 0x10, 0x04, 0x2a, 0x59, 0x0a, 0x0b, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x10, 0x00, 0x12, 0x11,
	0x0a, 0x0d, 0x52, 0x45, 0x56, 0x45, 0x52, 0x53, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x4f, 0x43, 0x4b, 0x53, 0x35, 0x10, 0x02, 0x12, 0x12, 0x0a,
	0x0e, 0x52, 0x45, 0x56, 0x45, 0x52, 0x53, 0x45, 0x5f, 0x53, 0x4f, 0x43, 0x4b, 0x53, 0x35, 0x10,
	0x03, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x53, 0x5f, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x10, 0x04, 0x2a,
	0x62, 0x0a, 0x0d, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x12, 0x18, 0x0a, 0x14, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4f,
	0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x5f, 0x5a, 0x4c, 0x49, 0x42, 0x10, 0x02,
	0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x5f, 0x5a, 0x53, 0x54,
	0x44, 0x10, 0x03, 0x2a, 0x4a, 0x0a, 0x0c, 0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c,
	0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0f,
	0x0a, 0x0b, 0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x5f, 0x52, 0x43, 0x34, 0x10, 0x02, 0x2a,
	0x65, 0x0a, 0x0a, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x09, 0x0a,
	0x05, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x4f, 0x47, 0x49,
	0x4e, 0x52, 0x53, 0x50, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x41, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f,
	0x4e, 0x47, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x05, 0x12, 0x0b,
	0x0a, 0x07, 0x4f, 0x50, 0x45, 0x4e, 0x52, 0x53, 0x50, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x43,
	0x4c, 0x4f, 0x53, 0x45, 0x10, 0x07, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proxy_proto_rawDescOnce sync.Once
	file_proxy_proto_rawDescData []byte
)

func file_proxy_proto_rawDescGZIP() []byte {
	file_proxy_proto_rawDescOnce.Do(func() {
		file_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)))
	})
	return file_proxy_proto_rawDescData
}

var file_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proxy_proto_goTypes = []any{
	(PROXY_PROTO)(0),         // 0: PROXY_PROTO
	(CLIENT_TYPE)(0),         // 1: CLIENT_TYPE
	(COMPRESS_TYPE)(0),       // 2: COMPRESS_TYPE
	(ENCRYPT_TYPE)(0),        // 3: ENCRYPT_TYPE
	(FRAME_TYPE)(0),          // 4: FRAME_TYPE
	(*LoginFrame)(nil),       // 5: LoginFrame
	(*LoginRspFrame)(nil),    // 6: LoginRspFrame
	(*PingFrame)(nil),        // 7: PingFrame
	(*PongFrame)(nil),        // 8: PongFrame
	(*OpenConnFrame)(nil),    // 9: OpenConnFrame
	(*OpenConnRspFrame)(nil), // 10: OpenConnRspFrame
	(*CloseFrame)(nil),       // 11: CloseFrame
	(*DataFrame)(nil),        // 12: DataFrame
	(*ProxyFrame)(nil),       // 13: ProxyFrame
}
var file_proxy_proto_depIdxs = []int32{
	0,  // 0: LoginFrame.proxyproto:type_name -> PROXY_PROTO
	1,  // 1: LoginFrame.clienttype:type_name -> CLIENT_TYPE
	2,  // 2: LoginFrame.compress_type:type_name -> COMPRESS_TYPE
	3,  // 3: LoginFrame.encrypt_type:type_name -> ENCRYPT_TYPE
	2,  // 4: LoginRspFrame.compress_type:type_name -> COMPRESS_TYPE
	3,  // 5: LoginRspFrame.encrypt_type:type_name -> ENCRYPT_TYPE
	2,  // 6: DataFrame.compress_type:type_name -> COMPRESS_TYPE
	4,  // 7: ProxyFrame.type:type_name -> FRAME_TYPE
	5,  // 8: ProxyFrame.loginFrame:type_name -> LoginFrame
	6,  // 9: ProxyFrame.loginRspFrame:type_name -> LoginRspFrame
	12, // 10: ProxyFrame.dataFrame:type_name -> DataFrame
	7,  // 11: ProxyFrame.pingFrame:type_name -> PingFrame
	8,  // 12: ProxyFrame.pongFrame:type_name -> PongFrame
	9,  // 13: ProxyFrame.openFrame:type_name -> OpenConnFrame
	10, // 14: ProxyFrame.openRspFrame:type_name -> OpenConnRspFrame
	11, // 15: ProxyFrame.closeFrame:type_name -> CloseFrame
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proxy_proto_init() }
func file_proxy_proto_init() {
	if File_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_proto_goTypes,
		DependencyIndexes: file_proxy_proto_depIdxs,
		EnumInfos:         file_proxy_proto_enumTypes,
		MessageInfos:      file_proxy_proto_msgTypes,
	}.Build()
	File_proxy_proto = out.File
	file_proxy_proto_goTypes = nil
	file_proxy_proto_depIdxs = nil
}
